#!/bin/bash

PACKAGE_NAME=`xmllint --xpath 'string(/addon/@id)' src/addon.xml`
ADDON_PATH="/Users/${USER}/Library/Application Support/Kodi/addons/${PACKAGE_NAME}"

rm -rf "${ADDON_PATH}"
ln -s $PWD/src "${ADDON_PATH}"
